ALTER PROC [dbo].[SP_LayThongTinTaiKhoan]
@TENLOGIN NVARCHAR (50)
AS
BEGIN
DECLARE @TENUSER NVARCHAR(50), @UID INT
SELECT @UID= uid, @TENUSER=name FROM sys.sysusers  WHERE sid = SUSER_SID(@TENLOGIN)
SELECT USERNAME = @TENUSER, 
	HOTEN = (SELECT HO+ ' '+ TEN FROM GIANGVIEN  WHERE MAGV = @TENUSER ),
	TENNHOM= NAME
	FROM sys.sysusers 
	WHERE UID = (SELECT GROUPUID FROM SYS.SYSMEMBERS 
                   WHERE MEMBERUID= @UID)
END
GO
EXEC SP_LayThongTinTaiKhoan 'PKT1'

